image: sknnr/vrising-dedicated-server
imageTag: latest
# serviceType should be LoadBalancer or NodePort
serviceType: LoadBalancer
resources:
  requests:
    memory: 16G
    cpu: 4.0
volumes:
  dataPVC:
    size: 50Gi
  storageClassName: ""
env:
  serverName: 'Skaz V Rising Server'
  gamePort: 27015
  queryPort: 27016
  description: 'Dedicated V Rising PvP Server'
  bindAddress: 0.0.0.0
  hideIpAddress: true
  lowerFPSWhenEmpty: true
  secure: true
  eosList: true
  steamList: false
  gamePreset: "StandardPvP"
  difficulty: "Difficulty_Normal"
  saveName: "vrising_world"
